remote_theme: pmarsceill/just-the-docs

title: REST-for-Physics
description: A comprehensive guide
#baseurl: "/" # the subpath of your site, e.g. /blog

#permalink: pretty

#exclude: ["README.md", "Rakefile" , "docs/tests/" ]

#logo: "/assets/images/RESTlogo.png"

#color_scheme: dark
#
# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/rest-for-physics/rest-for-physics.github.io" # the github URL for your repo
gh_edit_branch: "development" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "edit" # "tree" or "edit" if you want the user to jump into the editor immediately


ga_tracking: G-N6WX17N2RD
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true by default)

callouts:
  warning:
    title: Danger
    color: red
    
   
