remote_theme: pmarsceill/just-the-docs

title: REST-for-Physics
description: A comprehensive guide
#baseurl: "/" # the subpath of your site, e.g. /blog

#permalink: pretty

#exclude: ["README.md", "Rakefile" , "docs/tests/" ]

#logo: "assets/images/RESTlogoFull.png"

#color_scheme: dark
